Upgrade mock files and their examples from z13 to z16
zhmcclient/python-zhmcclient pull request #1225
Opened 2023-07-30 11:00 UTC by kavinrajam

As mentioned in issue [https://github.com/issues/1133] Changed the mocked file for z13 to z16 configuration

2023-07-30 11:00 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 403c58895fd85821d7287e0dbccebfb1c74613b5
  * Invalid signoff. Commit message must end with  
    **Signed-off-by: .* <.*>**

Guidelines are available at https://github.com/zhmcclient/python-zhmcclient/blob/master/CONTRIBUTING.rst

---
This message was auto-generated by https://gitcop.com

2023-07-30 14:04 UTC, andy-maier requested changes
The changes look good, but please add a signature to the commit message by using the `-s` option of git, i.e. `git -s --amend; git push -f`

2023-08-03 13:42 UTC, andy-maier commented
Merged without signature, to make progress.

2023-08-03 13:42 UTC, andy-maier approved these changes

2023-08-03 13:42 UTC, merged