Add example for load-from-ftp
zhmcclient/python-zhmcclient pull request #1346
Opened 2023-11-22 10:35 UTC by smitterl

Add example to use load-from-ftp for automated LPAR installation.

The session-credential can be used to connect to the API message broker. Store it as a new property.

Tested on a z16 with API 2.26

2023-11-22 13:49 UTC, andy-maier requested changes
Sebastian, thanks for this contribution.

The test workflow fails because the zhmcclient mock support does not return the session-credentials property from its mocked logon operation. Can you please add that as well?

2023-11-29 07:50 UTC, andy-maier commented
I may be asking for too much here. I'll create issues for the missing mock support, and the use of session-credentials and then will integrate your example script. Stay tuned.

2023-11-29 12:17 UTC, smitterl commented
> I may be asking for too much here. I'll create issues for the missing mock support, and the use of session-credentials and then will integrate your example script. Stay tuned.

Hi @andy-maier. Sorry for the late answer. I just added the commit.

2023-12-18 15:55 UTC, andy-maier approved these changes

2023-12-18 15:55 UTC, merged