Added zhmcclient mock support for "Get Partitions Assigned to Adapter" operation
zhmcclient/python-zhmcclient pull request #1557
Opened 2024-06-23 04:55 UTC by andy-maier

2024-06-23 09:21 UTC, anilak11 requested changes

2024-06-23 10:12 UTC, andy-maier commented on zhmcclient_mock/_urihandler.py
> +            for nic in partition.nics.list():
Very good catch. I was (too narrowly) looking only at network adapters...

2024-06-23 12:02 UTC, andy-maier commented on zhmcclient_mock/_urihandler.py
> +            for nic in partition.nics.list():
I have added support for crypto cards and accelerator cards.

The support for ficon cards depends on the newly created issue #1557, the code to support them as been commented out again and marked with an according TODO.

The support for all other adapters has been marked as a TODO.

2024-06-23 12:25 UTC, andy-maier commented on zhmcclient_mock/_urihandler.py
> +            for nic in partition.nics.list():
I have et this PR to "waiting", to be resumed after issue #1557 is resolved.

2024-06-23 12:25 UTC, andy-maier commented
I have set this PR to "waiting", to be resumed after issue https://github.com/zhmcclient/python-zhmcclient/pull/1557 is resolved.

2024-06-24 07:12 UTC, EdGue42 approved these changes

2024-06-27 09:37 UTC, andy-maier commented
Separated the enabling of the check for success from this PR into a separate one, so that this PR can pass and be merged.

2024-06-27 09:49 UTC, merged