timeout added to allow hmc to wait for partition to stop
zhmcclient/python-zhmcclient pull request #685
Opened 2020-11-03 15:00 UTC by jitunair18

- Observed that the hmc api to stop partition does not update the status of the partition to stopped state despite the api returning a job 'complete' status.
- This additional waiting check is similar to the code in start() function which waits for the partition status to reflect to it's correct status.

2020-11-03 15:00 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 0d5cc0e42196d868561f6bb061eb37eb57b2fddb
  * Invalid signoff. Commit message must end with  
    **Signed-off-by: .* <.*>**

Guidelines are available at https://github.com/zhmcclient/python-zhmcclient/blob/master/CONTRIBUTING.rst

---
This message was auto-generated by https://gitcop.com

2020-11-23 07:02 UTC, andy-maier requested changes
I have these comments:
* Rebase on latest master.
* Resolve the gitcop issue by adding a signoff line (use the `-s` option of `git commit`).
* Add a short commit message after the text that mentions the method and the new parameter.
* Add a short entry to the "Enhancements" section of the change log about the new parameter.

Otherwise, approved.

2020-12-18 16:30 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 0d5cc0e42196d868561f6bb061eb37eb57b2fddb
  * Invalid signoff. Commit message must end with  
    **Signed-off-by: .* <.*>**

 * Commit: d00d50fd954a4a8bbfe192b6af98d3fef0c69438
  * Invalid signoff. Commit message must end with  
    **Signed-off-by: .* <.*>**

Guidelines are available at https://github.com/zhmcclient/python-zhmcclient/blob/master/CONTRIBUTING.rst

---
This message was auto-generated by https://gitcop.com

2020-12-18 16:46 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: a09538157c3873c33677847d8260f2a8934b2c75
  * Invalid signoff. Commit message must end with  
    **Signed-off-by: .* <.*>**

Guidelines are available at https://github.com/zhmcclient/python-zhmcclient/blob/master/CONTRIBUTING.rst

---
This message was auto-generated by https://gitcop.com

2020-12-20 13:31 UTC, andy-maier commented
Replaced by PR #699.

2020-12-20 13:31 UTC, closed without merging