lpar: Fix body issue with STOP operation
zhmcclient/python-zhmcclient pull request #828
Opened 2021-08-30 16:42 UTC by eaibmz

This fixes the following problem:

$ zhmc -o json lpar stop --yes --allow-status-exceptions CPC LPAR
Error: HTTPError: 400,4: A content-length was specified but a body was not expected by this provider. [POST /api/logical-partitions/xxx/operations/stop]

According to the HMC REST API 2.15, the LPAR STOP operation doesn't expect
any body, not even an empty one.

See "Hardware Management Console Web Services API Version 2.15.0",
"Chapter 11. Core IBM Z resources", "Stop Logical Partition".

Signed-off-by: Alexander Egorenkov <egorenar@linux.ibm.com>

2021-08-30 16:42 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9689b3fc3b3595ec4e216fe71285bee742292841
  * Your commit message body contains a line that is longer than 80 characters

Guidelines are available at https://github.com/zhmcclient/python-zhmcclient/blob/master/CONTRIBUTING.rst

---
This message was auto-generated by https://gitcop.com

2021-08-30 17:00 UTC, steffen-maier approved these changes
Reviewed-by: Steffen Maier <maier@linux.ibm.com>

2021-08-30 17:07 UTC, mhartmay approved these changes
Thanks for fixing this.

2021-08-30 17:37 UTC, mhartmay commented
Please fix this line https://github.com/zhmcclient/python-zhmcclient/blob/bdf9b044ccd8e321921ed38b7d6c409413e15a6a/zhmcclient/_lpar.py#L961 as well. It has to be             
`statuses = ["not-operating"]`

2021-08-30 17:44 UTC, mhartmay approved these changes
Thanks.

2021-08-30 18:08 UTC, steffen-maier requested changes

2021-08-30 18:32 UTC, steffen-maier approved these changes
Reviewed-by: Steffen Maier <maier@linux.ibm.com>

2021-08-31 11:04 UTC, andy-maier commented
@eaibmz @mhartmay @steffen-maier Hi guys. Thanks for creating this PR and for reviewing it. It will be in the next minor version 1.1.0, and I will roll it back to the next fix version 1.0.2.

2021-08-31 18:12 UTC, merged

2021-08-31 18:18 UTC, andy-maier commented
PR #831 adds this change to the change log.