Added support for HMC definitions in Ansible inventory/vault format
zhmcclient/python-zhmcclient pull request #987
Opened 2022-05-01 13:52 UTC by andy-maier

See commit message.

2022-05-12 11:03 UTC, andy-maier commented on examples/example_hmc_vault.yaml
> +#       hmc_ca_certs: <hmc_ca_certs>
The auth parameters need to be named so they are compatible with the hmc_auth parameter of the zhmc Ansible modules, i.e. `userid`, `password`, `verify`, `ca_certs`.

2022-05-13 00:11 UTC, vkathir82 requested changes
For ansible modules to work changes required in example_hmc_inventory.yaml format

2022-05-14 07:36 UTC, andy-maier commented on examples/example_hmc_vault.yaml
> +#       hmc_ca_certs: <hmc_ca_certs>
done

2022-05-14 07:38 UTC, andy-maier commented on examples/example_hmc_inventory.yaml
> +  HMC1:
done

2022-05-14 10:32 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 84ef083d23ff0a23bde62c73a5a5cd183f25cd67
  * Your commit message body contains a line that is longer than 80 characters

Guidelines are available at https://github.com/zhmcclient/python-zhmcclient/blob/master/CONTRIBUTING.rst

---
This message was auto-generated by https://gitcop.com

2022-05-14 10:53 UTC, merged